### ISSUE TITLE
STLink crashes after a while when browsing files on micropython volumes

### ISSUE THREAD

**Issue by stepansnigirev** [diybitcoinhardware/f469-disco#6]
The bug was introduced with the last dual-flash-storage update of micropython submodule.
https://github.com/diybitcoinhardware/f469-disco/commit/0b4334cd0c978724133e1f54323acbe50d9c0cec

Not sure what is causing it, but STLink works if you don't connect microUSB cable for REPL and PYBFLASH/PYBQSPI , when I connect microUSB and start interacting with micropython STLink crashes after some time.

@miketlk maybe you have an idea?

**Comment by miketlk** [comment]
I usually leave both cables connected all the time. Before using STLink I always unmount all PYB* devices, otherwise, they are often corrupted, especially the PYBFLASH. That is not exactly your issue but could be useful.

I will check again with the version you mentioned (0b4334c) and the previous one.

**Comment by stepansnigirev** [comment]
can't reproduce it anymore, closing for now.
